name: Release automation

on:
  push:
    branches:
      - feature/automate-release
  # release:
  #   types:
  #     - edited

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - uses: delaguardo/setup-clojure@9.5
        with:
          lein: 2.9.5
      - run: lein deploy github

  clojars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - uses: delaguardo/setup-clojure@9.5
        with:
          lein: 2.9.5
      - run: lein deploy clojars
